apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: hello
        image: registry.redhat.io/ubi8/ubi-minimal
        command: ["/bin/sh","hostname -o"]
      restartPolicy: Never

